# /*****************************************************************************
#  ________          ___ ________  ________          ________  ________  ___  ___     
# |\_____  \        /  /|\   __  \|\   __  \        |\   ____\|\   __  \|\  \|\  \    
#  \|___/  /|      /  //\ \  \|\  \ \  \|\  \       \ \  \___|\ \  \|\  \ \  \\\  \   
#      /  / /     /  //  \ \   __  \ \  \\\  \       \ \  \    \ \   ____\ \  \\\  \  
#     /  /_/__   /  //    \ \  \|\  \ \  \\\  \       \ \  \____\ \  \___|\ \  \\\  \ 
#    |\________\/_ //      \ \_______\ \_______\       \ \_______\ \__\    \ \_______\
#     \|_______|__|/        \|_______|\|_______|        \|_______|\|__|     \|_______|
                                                                                    
# MIT License

# Copyright (c) 2022 Mike Sharkey

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ******************************************************************************
TARGET=z80.s19

# GNU assembler toolchain programs.
AS = z80-unknown-coff-as
LD = z80-unknown-coff-ld

# C compilation directives
AFLAGS += ${LIBZ80_AFLAGS}

# Header file directories.
INCLUDE += -I ./

# Z/80 CPU Source Files
ASRC  += abi.s
ASRC  += int32.s
ASRC  += main.s

# Object files to build.
OBJS += $(ASRC:.s=.o)

# Default rule to build the whole project.
.PHONY: all
all: $(TARGET)

# Rule to compile C files.
%.o: %.cpp
	$(AS) $(AFLAGS) $(INCLUDE) $< -o $@

# Rule to create an ELF file from the compiled object files.
$(TARGET): $(OBJS)
	$(LD) -e main --oformat srec -o $@  $^ $(LIBS)

# Rule to clear out generated build files.
.PHONY: clean
clean:
	rm -f $(OBJS) $(TARGET)

